name: 'Build and test C++ Project'
description: 'Builds and tests C++ projects following a specific format.'
inputs:
  mode:
    description: 'Installing dependencies, building, or upload.'
    required: True
  package_name:
    description: 'The name of the package'
    required: true
  arch:
    description: 'What architecture to build for'
    required: true
  compiler:
    description: 'What compiler to build with'
    required: true
  username:
    description: 'Username used to log in to the gitea instance'
    required: false
  password:
    description: 'Password or personal access token used to log to the gitea instance'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
